### ISSUE TITLE
please try 5*8 ,the result is error

### ISSUE THREAD

**Issue by vipheyue** [uklimaschewski/EvalEx#146]
<img width="546" alt="qq20171218-180800 2x" src="https://user-images.githubusercontent.com/11717882/34100749-7388406e-e41e-11e7-93f2-836da5bf27a7.png">

**Comment by RobertZenz** [comment]
That is not an error, that is the result [expressed as E notation](https://en.wikipedia.org/wiki/Scientific_notation#E-notation). Which is also not a problem of EvalEx (because it is not concerned with how numbers are displayed). Seems more like the code that is responsible for displaying the number screwed up.

**Comment by vipheyue** [comment]
How to display normal numerical results 😅

**Comment by uklimaschewski** [comment]
`Expression.eval()` returns a `java.math.BigDecimal`. The `toString()` method of `BigDecimal` uses scientific notation. Use `Expression.eval().toPlainString()` instead.

**Comment by vipheyue** [comment]
thanks,you are intelligent 👍

**Comment by vipheyue** [comment]
thanks,you are intelligent 👍 @uklimaschewski

**Comment by vipheyue** [comment]
thanks,you are intelligent 👍 @uklimaschewski @RobertZenz
