### ISSUE TITLE
Deal with Non-breaking space in StringTokenizer in Expression.java line 460/461

### ISSUE THREAD

**Issue by RoiSoleil** [uklimaschewski/EvalEx#154]
Deal with Non-breaking space in StringTokenizer in Expression.java line 460/461

**Comment by uklimaschewski** [comment]
@RoiSoleil can you elaborate what is the problem? Do you have any test case that fails?

**Comment by RoiSoleil** [comment]
On lines 460/461, you use ' ' but with non-breaking space (ascii 255) it doesn't work.

**Comment by RobertZenz** [comment]
@RoiSoleil ASCII only goes to 127, did you mean Unicode? Though, in Unicode/UTF-8 a non-breaking space is encoded as 0xa0 (160). Can you elaborate on how you ended up with such a character in the string?

**Comment by RoiSoleil** [comment]
Sorry extended ascii.
http://www.theasciicode.com.ar/extended-ascii-code/non-breaking-space-no-break-space-ascii-code-255.html
But it's the same problem for Unicode/UTF-8. 
How : I have a GUI that allow users to create an 'Expression' and they can enter NBSP, it how i end up with NBSP in my string. But i could eventually replace all NBSP by SP in a preprocess, so it's not a big deal.

**Comment by RobertZenz** [comment]
Ah, okay, the [Extended ASCII table on Wikipedia](https://en.wikipedia.org/wiki/Extended_ASCII) looks a little bit different.

Maybe using `Character.isWhitespace(char)` would be an option, though, I do not know from the top of my head whether that us considering an NBSP as whitespace, but I guess so. That would also solve "problems" with tabs, for example. I'd have to test that, though.

**Comment by uklimaschewski** [comment]
I have committed a change to use `Character.isWhiteSpace(ch)`instead of `ch == ' '` (Commit 5d9db79516070c1cfb1395891de45d9757fe188a).
This will **not** help for ASCII 0xFF, I have tested it. I think this kind of special characters have to be handled prior to feeding it to the `Expression`class.
The JavaDoc says about `isWhiteSpace()`:

Determines if the specified character is white space according to Java. A character is a Java whitespace character if and only if it satisfies one of the following criteria: 
• It is a Unicode space character (SPACE_SEPARATOR, LINE_SEPARATOR, or PARAGRAPH_SEPARATOR) **but is not also a non-breaking space** ('\u005Cu00A0', '\u005Cu2007', '\u005Cu202F'). 
• It is '\u005Ct', U+0009 HORIZONTAL TABULATION. 
• It is '\u005Cn', U+000A LINE FEED. 
• It is '\u005Cu000B', U+000B VERTICAL TABULATION. 
• It is '\u005Cf', U+000C FORM FEED. 
• It is '\u005Cr', U+000D CARRIAGE RETURN. 
• It is '\u005Cu001C', U+001C FILE SEPARATOR. 
• It is '\u005Cu001D', U+001D GROUP SEPARATOR. 
• It is '\u005Cu001E', U+001E RECORD SEPARATOR. 
• It is '\u005Cu001F', U+001F UNIT SEPARATOR.

**Comment by RoiSoleil** [comment]
Ok good for me too.

**Comment by RobertZenz** [comment]
@RoiSoleil Now that I think about it, all `String`s in Java are UTF-16, so they should not contain 0xff to begin with.

**Comment by uklimaschewski** [comment]
I'll close this topic for now. If it needs further discussion, it can be reopened.
