### ISSUE TITLE
Make LazyNumber an outer interface and add an accessor to add variable of LazyNumber type

### ISSUE THREAD

**Issue by RoiSoleil** [uklimaschewski/EvalEx#155]
Make LazyNumber an outer interface and add an accessor to add variable of LazyNumber type

**Comment by uklimaschewski** [comment]
Sorry for the late answer, @RobertZenz @RoiSoleil .
If you want to do this, Robert, I'd be happy. I am very busy at the moment with other projects and my job.

**Comment by RobertZenz** [comment]
@uklimaschewski No worries. I'll look into it.

**Comment by uklimaschewski** [comment]
In your PR, you mentioned that probably externalizing `LazyNumber` isn't necessary, because it is a public interface.
So, the following is possible, also outside of the `Expression` class:
```Java
		LazyNumber ln = new LazyNumber() {
			@Override
			public String getString() {
				return "whatever";
			}
			@Override
			public BigDecimal eval() {
				return BigDecimal.ZERO;
			}
		};
```
So, I think the only thing that is needed are two new methods:
```Java
public Expression with(String variable, LazyNumber value);
public Expression and(String variable, LazyNumber value);
```
I see it the same, especially as externalizing `LazyNumber` would break backward compatibility too much.

**Comment by RoiSoleil** [comment]
It's ok for me if we only have the  second commit.

`public Expression with(String variable, LazyNumber value);
public Expression and(String variable, LazyNumber value);`

**Comment by uklimaschewski** [comment]
I merged your PR, @RobertZenz . Thanks alot.

**Comment by RoiSoleil** [comment]
Thx
