### ISSUE TITLE
*Missing parameters for operator +* while using sin(a+x)

### ISSUE THREAD

**Issue by iamsubhranil** [uklimaschewski/EvalEx#98]
If I use `(a+x)` and leave `a` unset, then the error pops up `"Unknown operator or function: a"`, which is 100% correct, but when I do the same thing with `sin(a+x)`, `Missing parameters for operator +` pops up. Moreover, I can't reuse that `Expression` object anymore to set the value of `a`, which pops up `"EmptyStackExpression"`. This is a bug or it is intentionally made to behave this way?

**Comment by squeek502** [comment]
What version are you using? Many `EmptyStackExpression` errors were fixed by #71, which is included in the [latest versions](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22EvalEx%22%20g%3A%22com.udojava%22).

Also, the specific text `Missing operands` does not appear anywhere in the source code, so if you're using the latest version, then a copy of the actual stack trace would be helpful.

**Comment by iamsubhranil** [comment]
My bad. Was in a bit hurry. Check now.

**Comment by iamsubhranil** [comment]
And I'm using the git fork. So it is the most lastest.

**Comment by squeek502** [comment]
Then, yes, this is a bug.

**Comment by uklimaschewski** [comment]
I have added a unit test and it correctly produces "Unknown operator or function: a" for sin(a+x).
